{{ if "mailer.createSecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mailer
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  password: {{ .Values.mailer.password | b64enc | quote }}
  MAILER_SMTP_DOMAIN: {{ .Values.mailer.smtp_domain | b64enc | quote }}
  MAILER_DOMAIN: {{ .Values.mailer.domain | b64enc | quote }}
  MAILER_USER_NAME: {{ .Values.mailer.user_name | b64enc | quote }}
  MAILER_PORT: {{ .Values.mailer.port | b64enc | quote }}
{{ end }}
