apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-task
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-migrate-task
      labels:
        name: {{ .Release.Name }}-migrate-task
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/sh","-c"]
          args: ["rake db:migrate && echo 'migrated successfully'"]
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config
